# -*- coding: utf-8 -*-
"""imports_exports_graphs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19yKhr8YJEsTz9V-wYv-crnt1vNP8KmGQ
"""

import pandas as pd 
#uploading the dataset 9th vintage
data=pd.read_stata("../unconditional_mac_sector_20e_weighted.dta")

#generating the ratio imports /rev 
data["exp"]=data["TV03_exp_adj_mn"]*data["TV03_exp_adj_sw"]
data["exp"]=pd.to_numeric(data["exp"])
data["revenues"]=data["FV08_nrev_mn"]*data["FV08_nrev_sw"]
data["revenues"]=pd.to_numeric(data["revenues"])

#generaring the ratio exports/ rev
data["exports"]= data["exp"]/data["revenues"]
data["impo"]=data["TV09_imp_adj_mn"]*data["TV09_imp_adj_sw"]
data["impo"]=pd.to_numeric(data["impo"])
data["imports"]=data["impo"]/data["revenues"]

#starting with imports, we take only data with values, which happens to exist only for the manufacturing sector
data1=data
data1=data1[data1["imports"]>0]
data1=data1[data1["mac_sector"]=='1 - Manufacturing']
100*data1[data1['year']==2020][["imports", "country"]].reset_index(drop=True)

#generating average imports from 2005 to 2019
100*data1[(data1["year"]>=2015)&(data1["year"]<=2019)].groupby("country").mean()[["imports"]]

#graph for imports where we compare years 2015-9 with 2020
import numpy as np 
import matplotlib.pyplot as plt 
  
X = ['Croatia ', ' CzechRep', '  Denmark', '  Finland', 
        'Lithuania', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Sweden']

Z2019 = [27.803091,
	37.797304,
31.868810,
20.720807,
36.879357,
50.998161,
27.796457,
31.061311,
35.340170,
53.966823,
54.621905,
28.571265]

Y2020 = [25.966524,
36.631608,
39.240543,
20.042678,
32.048335,
39.432334,
0,
28.868096,
34.543251,
51.595741,
53.118630,
25.817319]

X_axis = np.arange(len(X))
fig, ax = plt.subplots(figsize=(18,8))
plt.bar(X_axis+0.2,Y2020,0.4, label = '2020', color='yellow')
plt.bar(X_axis-0.2, Z2019, 0.4,label = '2015-2019')
plt.rc('font', size=10)
plt.tick_params(axis='both', labelsize=15)
plt.xticks(X_axis, X)  
plt.title("Import share on revenues (%)", fontsize=20)
plt.legend(loc='upper center')

plt.show()

#now we do the same for exports
data=data[data["exports"]>0]
data.groupby("mac_sector").count()[["country"]]

data=data[data["mac_sector"]=='1 - Manufacturing']
len(data)

100*data[data['year']==2020][["exports", "country"]].reset_index(drop=True)

100*data[(data["year"]>=2015)&(data["year"]<=2019)].groupby("country").mean()[["exports"]]

#graph for EXPORTS 
import numpy as np 
import matplotlib.pyplot as plt 
  
X = ['Croatia ', ' CzechRep', '  Denmark', '  Finland', '  France','Germany',
       'Hungary ', 'Lithuania', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Sweden']

Z2019 = [46.162338,
58.995235,
67.470627,
43.591362,
49.658195,
46.401375,
87.717514,
60.090614,
62.883480,
47.663807,
50.043278,
57.651150,
73.738441,
75.857185,
80.659035,
56.785477]

Y2020 = [45.549088,
	59.157669,
	81.953255,
	42.207191,
	43.647572,
0,
	80.540817,
	59.934406,
	56.865788, 
0,
	50.551594,
	55.439568,
	69.879356,
	70.184402,
	81.535706,
	55.524570]

X_axis = np.arange(len(X))
fig, ax = plt.subplots(figsize=(18,8))
plt.bar(X_axis+0.2,Y2020,0.4, label = '2020', color='yellow')
plt.bar(X_axis-0.2, Z2019, 0.4,label = '2015-2019')
plt.rc('font', size=10)
#plt.tick_params(axis='both', labelsize=15)
plt.xticks(X_axis, X)  
plt.title("Export share on revenues (%)", fontsize=20)
plt.legend(loc='upper center')

plt.show()